// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Sandbox specification for nodes that execute untrusted code.
 * Declares what the sandbox environment needs (system packages, resource limits, network).
 * The runner infrastructure handles the actual isolation (nsjail on Linux, direct on dev).
 */
export type SandboxSpec = { 
/**
 * System packages required inside the sandbox (e.g., ["ffmpeg", "imagemagick"]).
 * These must be pre-installed in the Docker image. Validated at startup.
 */
system_packages: Array<string>, 
/**
 * Max CPU time in seconds
 */
cpu_limit_secs: number, 
/**
 * Max memory in MB
 */
memory_limit_mb: number, 
/**
 * Max wall-clock execution time in seconds
 */
timeout_secs: number, 
/**
 * Allow outbound network access (internal IPs are always blocked)
 */
allow_network: boolean, };
